modLoader = "javafml"
loaderVersion = "[1,)"
license = "All rights reserved"

[[mods]]
modId = "tinactory_datagen"
version = "${mod_version}"
displayName = "Tinactory Datagen"
authors = "Tiny"

[[dependencies.tinactory_datagen]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinactory_datagen]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinactory_datagen]]
modId = "tinycorelib"
type = "required"
versionRange = "[1.21.1-0.0.3.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinactory_datagen]]
modId = "tinydatagen"
type = "required"
versionRange = "[1.21.1-0.0.3.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinactory_datagen]]
modId = "tinactory"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
